// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfDtZTAr5Y-vYWORmucHudCB5aHN5BIMw',
    appId: '1:825137302078:web:379356f9601b91b706df6f',
    messagingSenderId: '825137302078',
    projectId: 'passwordless-auth-e89fd',
    authDomain: 'passwordless-auth-e89fd.firebaseapp.com',
    storageBucket: 'passwordless-auth-e89fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvARE_EhWVQuarqPX3VtPiLmuKRFSQ1_8',
    appId: '1:825137302078:android:7e73d3b6311015b706df6f',
    messagingSenderId: '825137302078',
    projectId: 'passwordless-auth-e89fd',
    storageBucket: 'passwordless-auth-e89fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpcNL4Sq8aL_0ds9AaNnG0i3Qf6V3M784',
    appId: '1:825137302078:ios:bf855cd20ac368db06df6f',
    messagingSenderId: '825137302078',
    projectId: 'passwordless-auth-e89fd',
    storageBucket: 'passwordless-auth-e89fd.appspot.com',
    iosClientId: '825137302078-fk5kvf5ugmgjlt5n2q9d0kng2tpqtu3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.passwordlessAuth',
  );
}
